### PR TITLE
Switch to `System.Text.Json`

### PR DESCRIPTION
**Pull request by twcrews**
This change removes the dependency on `Newtonsoft.Json` in favor of its built-in `System.Text.Json` counterpart.

### CODE REVIEW

**Comment by scott-mcdonald** [comment]
@twcrews First I thank you for taking on a big refactor/feature. So let me give you the bad news first, `JsonApiFramework` would need to be backwards compatible to `Newtonsoft.Json` as there are higher level projects that have that dependency. Therefore the feature you need to implement would be `JsonApiFramework` being agnostic about the JSON serialization/deserialization implementation and be able to use either `Newtonsoft.Json` or `System.Text.Json` respectively.

Once such design would be to abstract the JSON serializer and deserializer via interfaces and using DI injecting implementations that used either `Newtonsoft.Json` or `System.Text.Json` respectively. Similar to the provider model EntityFrameworkCore has implemented. This is a big feature, nontrivial for sure but is the proper way this needs to be done.

If you don't want to do that, your next best option is to fork this repository and do the changes that pulls out  `Newtonsoft.Json` and uses `System.Text.Json` instead...

**Comment by twcrews** [comment]
@scott-mcdonald I appreciate the feedback. I'll go ahead and close this for now. 

I'll see about what that implementation might look like. If it ends up being too much of a lift, I will just take your advice and keep the fork for my own use. Thanks!

**Comment by lol768** [comment]
I would argue for a breaking, major version change that just drops Newtonsoft altogether.

If there are higher-level projects that are assuming its presence, that seems like a problem with assumptions those other projects are making. The world has moved on and STJ is the standard now.

Ultimately the insistence here on an abstraction layer has just meant that this PR didn't end up shipping at all.

In the org I work for, `JsonApiFramework` is one of the last (if not the only?) NuGet packages we make use of that introduces a requirement to use Newtonsoft - which causes a world of pain for us and leads to codebases that then need to use both attributes at the same time (or duplicate all of the models), write custom converters twice etc. It's a real shame, because I can't argue with the goals of the JSON:API spec and the problems it's trying to solve.

**Comment by scott-mcdonald** [comment]
@lol768 For your edification JSON.NET was the only real C# JSON library worth using back in 2016 when this was started and yes JsonApiFramework is heavily dependent on JSON.NET by essentially hooking heavily into it's framework level classes.

I also agree with your statement about System.Text.Json being the standard as of today as well. Instead of working on JsonApiFramework though, I am working on a more general ApiFramework which has accepted Microsoft standards for JSON and logging for example instead of trying to abstract away these low-level features via "Interface Segregation" principle, etc.

There are some higher-level frameworks that I built on top of JsonApiFramework. I think those ideas and features are solid and therefore I want to assemble it all together in a more general "ApiFramework" that has a provider model with the first provider being JSON:API. To me that is the future for myself... With that said, ApiFramework will not be available for awhile but a work in progress.

To circle back to your original premise though and be fully transparent, I don't have time to take on dropping Newtonsoft from JsonApiFramework even though I agree with you...

**Pull request closed without merging**
