### PR TITLE
Expose the AddCamelCaseNamingConvention method to the INamingConventionsBuilder interface

### PR DESCRIPTION
**Pull request by lopes-felipe**

### CODE REVIEW

**Comment by lopes-felipe** [comment]
Thank's for the merge. 

Any ideia on when will it be available at Nuget?

**Comment by scott-mcdonald** [comment]
I should have time tonight to push it up to nuget, in other words should be available sooner rather then later. Thanks for the pull request.

**Comment by scott-mcdonald** [comment]
Pushed to nuget. Look for update to v1.3.0-beta...

**Comment by lopes-felipe** [comment]
Great! Thank you very much indeed :)

**Pull request merged**
